### ISSUE TITLE
Combine copiedTooltipColor and tooltipColor

### ISSUE THREAD

**Issue by tobias-mintlify** [mintlify/components#46]
We tried using separate colors in `mint` for the code block's copy tooltip but it looked odd having the color change when you click.

We should use the same hex color for both and delete the `copiedTooltipColor` prop.

**Comment by sboy99** [comment]
Hey @tobias-mintlify  I'm interested to work on this. Just want to clarify some things, In this changes I have to only remove the `copiedTooltipColor` prop. as it is assigned with the ` tooltipColor` and have to remove `hidden` conditional in the tooltip functional call. It would be great if you confirm this.

**Comment by tobias-mintlify** [comment]
Welcome to the repo @sboy99 !

You should keep the `hidden` conditional. All this ticket requires is that you remove the `copiedTooltipColor` prop and use `tooltipColor` instead :)
