### ISSUE TITLE
Callback when clipboard is clicked on code blocks

### ISSUE THREAD

**Issue by tobias-mintlify** [mintlify/components#47]
We want [mint](https://github.com/mintlify/mint) to send [analytics events](https://mintlify.com/docs/analytics/supported-integrations) when the user copies from a code block.

We need an optional prop on the CodeBlock and CodeGroup component that runs whenever the clipboard is clicked. The event should have `name` and `code` as event properties.

**Comment by tobias-mintlify** [comment]
We might be able to use Storybook interactions to test the event fires?

**Comment by NicoZweifel** [comment]
Going to take this one, I'll add Actions/Interactions in storybook.

**Comment by hanywang2** [comment]
@NicoZweifel we just had to do this for #51

**Comment by NicoZweifel** [comment]
No problem ☺️
