### ISSUE TITLE
Cards should accept an image prop

### ISSUE THREAD

**Issue by hanywang2** [mintlify/components#57]
# Summary

Card right now only accepts `icons`. However, a true `Card` should have an `image` property that sits above the card and covers the entire spacing like so

<img width="433" alt="CleanShot 2023-02-07 at 23 03 30@2x" src="https://user-images.githubusercontent.com/44352119/217457997-4ac466ba-2f38-4c56-b7ae-ef71e0821631.png">

**Comment by sboy99** [comment]
Interested! I think it is almost the same as icon prob but it will only take string props. And will be rendered on top to the card. Assign me I will try my best.

**Comment by sboy99** [comment]
@tobias-mintlify  should I start working on this I'm really looking forward to contribute.

**Comment by tobias-mintlify** [comment]
@sboy99 Yes, no one has started on this so it would be great for you! Sorry I didn't see your message yesterday.

**Comment by sboy99** [comment]
![Screenshot from 2023-02-13 16-57-32](https://user-images.githubusercontent.com/86586277/218445918-cb18bec3-9e97-4b07-ab12-c5c2e6329b3c.png)

Almost done, One query what would be be the maximum height? As in large screen this is happening
 
![Screenshot from 2023-02-13 17-01-19](https://user-images.githubusercontent.com/86586277/218446621-7b2ac3e7-47e0-41da-b632-189ff488950a.png)

**Comment by tobias-mintlify** [comment]
What about `h-64`? That's 256px in TailwindCSS
