### ISSUE TITLE
Core Mint repo privated?

### ISSUE THREAD

**Issue by davidlinc1** [mintlify/components#81]
Hey folks, just noticed the core Mint repo with the client seems to have been made private and was just curious if there are plans to bring it back. Maybe you know more @tobias-mintlify? Sorry for cross-posting to this repo, feel free to tag as off-topic / delete / ignore.

**Comment by hanywang2** [comment]
Hey @davidlinc1 thanks for asking! We're currently in the process of rebuilding mint and launching from a new repo. It will be up again and public soon
